name: siercp
description: Sistema Inteligente de Entrenamiento de Reanimación Cardiopulmonar
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Navegación
  go_router: ^13.0.0

  # Estado
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.5.4
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.1.4
  firebase_database: ^11.3.10

  # Gráficas
  fl_chart: ^0.68.0

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  lottie: ^3.1.0

  # Utilitarios
  intl: ^0.19.0
  uuid: ^4.4.0
  connectivity_plus: ^6.0.3
  permission_handler: ^11.3.1
  http: ^1.6.0
  shared_preferences: ^2.5.5

  # Exportación PDF / CSV
  pdf: ^3.10.8
  share_plus: ^7.2.2
  path_provider: ^2.1.2
  printing: ^5.13.1
  syncfusion_flutter_gauges: ^33.1.45
  syncfusion_flutter_pdfviewer: ^33.2.3
  file_picker: ^8.1.7

  # BLE & Audio
  flutter_blue_plus: ^2.2.1
  audioplayers: ^6.6.0

  # Almacenamiento Local Offline (SQLite)
  sqflite: ^2.4.2

  # Para abrir archivos guardados
  open_filex: ^4.5.0
  screenshot: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.2
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
  fonts:
    - family: SpaceMono
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
        - asset: assets/fonts/SpaceMono-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
